const htmlElements = [
  { name: "a" },
  { name: "abbr" },
  { name: "acronym", deprecated: true },
  { name: "address" },
  { name: "applet", deprecated: true },
  { name: "area" },
  { name: "article" },
  { name: "aside" },
  { name: "audio" },
  { name: "b" },
  { name: "base" },
  { name: "basefont", deprecated: true },
  { name: "bdi" },
  { name: "bdo" },
  { name: "bgsound", deprecated: true, nonStandard: true },
  { name: "big", deprecated: true },
  { name: "blink", deprecated: true },
  { name: "blockquote" },
  { name: "body" },
  { name: "br" },
  { name: "button" },
  { name: "canvas" },
  { name: "caption" },
  { name: "center", deprecated: true },
  { name: "cite" },
  { name: "code" },
  { name: "col" },
  { name: "colgroup" },
  { name: "content", deprecated: true },
  { name: "data" },
  { name: "datalist" },
  { name: "dd" },
  { name: "del" },
  { name: "details" },
  { name: "dfn" },
  { name: "dialog" },
  { name: "dir", deprecated: true },
  { name: "div" },
  { name: "dl" },
  { name: "dt" },
  { name: "em" },
  { name: "embed" },
  { name: "fieldset" },
  { name: "figcaption" },
  { name: "figure" },
  { name: "font", deprecated: true },
  { name: "footer" },
  { name: "form" },
  { name: "frame", deprecated: true },
  { name: "frameset", deprecated: true },
  { name: "head" },
  { name: "header" },
  { name: "h1" },
  { name: "hgroup", deprecated: true, experimental: true },
  { name: "hr" },
  { name: "html" },
  { name: "i" },
  { name: "iframe" },
  { name: "image", deprecated: true, nonStandard: true },
  { name: "img" },
  { name: "input" },
  { name: "ins" },
  { name: "kbd" },
  { name: "keygen", deprecated: true },
  { name: "label" },
  { name: "legend" },
  { name: "li" },
  { name: "link" },
  { name: "main" },
  { name: "map" },
  { name: "mark" },
  { name: "marquee", deprecated: true },
  { name: "menu", experimental: true },
  { name: "menuitem", deprecated: true },
  { name: "meta" },
  { name: "meter" },
  { name: "nav" },
  { name: "nobr", deprecated: true, nonStandard: true },
  { name: "noembed", deprecated: true, nonStandard: true },
  { name: "noframes", deprecated: true },
  { name: "noscript" },
  { name: "object" },
  { name: "ol" },
  { name: "optgroup" },
  { name: "option" },
  { name: "output" },
  { name: "p" },
  { name: "param" },
  { name: "picture" },
  { name: "plaintext", deprecated: true },
  { name: "portal" },
  { name: "pre" },
  { name: "progress" },
  { name: "q" },
  { name: "rb", deprecated: true },
  { name: "rp" },
  { name: "rt" },
  { name: "rtc", deprecated: true },
  { name: "ruby" },
  { name: "s" },
  { name: "samp" },
  { name: "script" },
  { name: "section" },
  { name: "select" },
  { name: "shadow", deprecated: true },
  { name: "slot" },
  { name: "small" },
  { name: "source" },
  { name: "spacer", deprecated: true },
  { name: "span" },
  { name: "strike", deprecated: true },
  { name: "strong" },
  { name: "style" },
  { name: "sub" },
  { name: "summary" },
  { name: "sup" },
  { name: "table" },
  { name: "tbody" },
  { name: "td" },
  { name: "template" },
  { name: "textarea" },
  { name: "tfoot" },
  { name: "th" },
  { name: "thead" },
  { name: "time" },
  { name: "title" },
  { name: "tr" },
  { name: "track" },
  { name: "tt", deprecated: true },
  { name: "u" },
  { name: "ul" },
  { name: "var" },
  { name: "video" },
  { name: "wbr" },
  { name: "xmp", deprecated: true },
];
